name: Go package

on:
  push:
    branches:
      - main
    paths:
      - "**/*.go"

jobs:
  create_release:
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Get current date
        shell: bash
        id: date
        run: |
          sudo timedatectl set-timezone Europe/Bratislava
          echo "::set-output name=date::$(date +'%H-%M-%S-%d-%m-%Y')"

      - name: Create release for build
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.date.outputs.date }}
          release_name: ${{ steps.date.outputs.date }}
          body: |
            Release for ${{ steps.date.outputs.date }}
          draft: false
          prerelease: false
  build_and_test:
    needs: create_release
    strategy:
      matrix:
        include:
          - os: "ubuntu-latest"
            bin: "pqcom"
          - os: "windows-latest"
            bin: "pqcom.exe"
    runs-on: ${{ matrix.os }}
    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Build
        run: go build -v -o ${{ matrix.bin }}

      - name: Test
        run: go test -v

      - name: Upload binary to release
        id: upload_binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_path: ${{ matrix.bin }}
          asset_name: ${{ matrix.bin }}
          asset_content_type: application/bin
