name: Go package

on:
  push:
    branches:
      - main
    paths:
      - "**/*.go"

jobs:
  create_release:
    runs-on: ubuntu-latest
    outputs:
      release_url: ${{ steps.create_release.outputs.release_url }}
    steps:
      - name: Create release
        id: create_release
        uses: SamoKopecky/.github/.github/actions/create-time-release@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

  build_and_test:
    needs: create_release
    strategy:
      matrix:
        include:
          - os: "ubuntu-latest"
            bin: "pqcom"
          - os: "windows-latest"
            bin: "pqcom.exe"
    runs-on: ${{ matrix.os }}
    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Build
        run: go build -v -o ${{ matrix.bin }}

      - name: Test
        run: go test -v

      - name: Upload binary to release
        id: upload_binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.release_url }}
          asset_path: ${{ matrix.bin }}
          asset_name: ${{ matrix.bin }}
          asset_content_type: application/bin
